name: Deploy smart contract to Sepolia ðŸš€
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js âš™ï¸
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Create env file
        run: |
          touch .env
          echo OWNER_ADDRESS=${{ secrets.OWNER_ADDRESS }} >> .env
          echo MANAGER_ADDRESS=${{ secrets.MANAGER_ADDRESS }} >> .env
          echo SEPOLIA_RPC_URL=${{ secrets.SEPOLIA_RPC_URL }} >> .env
          echo ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }} >> .env
          echo PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} >> .env
      - name: Install dependencies ðŸ“¦
        run: yarn install
      - name: Run tests ðŸ’¡
        run: yarn test
      - name: Deploy to network
        id: deploy
        run: >-
          echo "CONTRACT_ADDRESS=$(
            yarn deploy-sepolia | grep -o '0x[0-9a-zA-Z]*'
          )"  >> $GITHUB_OUTPUT
      - name: Verify deployed contract
        run: yarn verify-sepolia ${{ steps.deploy.outputs.CONTRACT_ADDRESS }} ${{ secrets.OWNER_ADDRESS }} ${{ secrets.MANAGER_ADDRESS }}
      - name: Print deployed contract address
        run: echo ${{ steps.deploy.outputs.CONTRACT_ADDRESS }}
      - name: Extract abi from hardhat artifact
        uses: sergeysova/jq-action@v2
        with:
          cmd: 'jq .abi ./artifacts/contracts/Subscription.sol/Subscription.json > ./contracts/SubscriptionABI.json'
      - name: Generate README.md
        run: |
          sed 's/{{CONTRACT_ADDRESS}}/${{ steps.deploy.outputs.CONTRACT_ADDRESS }}/g' templates/README.md.tpl > /tmp/README.md
          sed 's/{{GITHUB_SHA}}/${{github.sha}}/g' /tmp/README.md > README.md
          sed -i '1s/^/\[\/\/\]\: # (GENERATED FILE DO NOT EDIT DIRECTLY)\n/' README.md
      - uses: stefanzweifel/git-auto-commit-action@v5